name: Development

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_DATABASE: testing_db
          MYSQL_ROOT_PASSWORD: password
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testing_db
      DB_USERNAME: root
      DB_PASSWORD: password
    steps:
      - name: PHP実行環境を展開する
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: 8
      - name: チェックアウトアクションを実行する
        uses: actions/checkout@v2
      - name: Laravelをセットアップする
        uses: ./.github/steps/setup-laravel
      - name: テストを実行する
        run: vendor/bin/phpunit
